fix: correct [graphrag/general/exactor.py change.removed_nodes.extend(nodes[1:])] AttributeError: 'set' object has no attribute 'extend' [AttributeError: 'set' object has no attribute 'nodes' TypeError: 'NoneType' object is not iterable] from commit ece5903