Squashed commit of the following:
commit 9b2ef62aeef358ac29044c1fc03ef6623eed758e
Author: Zhichang Yu <yuzhichang@gmail.com>
Date:   Fri Dec 13 17:31:15 2024 +0800

    Fix xinfo_groups returns unexpected result (#4026)

    ### What problem does this PR solve?

    Fix xinfo_groups returns unexpected result. Close #3545

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

commit 86507af770cae6b63fa0c9eab139461aa697ba5f
Author: Zhichang Yu <yuzhichang@gmail.com>
Date:   Fri Dec 13 17:15:08 2024 +0800

    Set task progress on exception (#4025)

    ### What problem does this PR solve?

    Set task progress on exception

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

commit 93635674c34d2466446c29fc77a36f291ec6825f
Author: balibabu <cike8899@users.noreply.github.com>
Date:   Fri Dec 13 16:55:13 2024 +0800

    Feat: Reparse a file shall reuse existing chunks if possible #3793 (#4021)

    ### What problem does this PR solve?

    Feat: Reparse a file shall reuse existing chunks if possible #3793

    ### Type of change

    - [x] New Feature (non-breaking change which adds functionality)

commit 1defe0b19bd27dd74cb1cb841eb802fee4a1269d
Author: balibabu <cike8899@users.noreply.github.com>
Date:   Fri Dec 13 14:43:24 2024 +0800

    Feat: Supports to debug single component in Agent. #3993 (#4007)

    ### What problem does this PR solve?

    Feat: Supports to debug single component in Agent. #3993
    Fix: The github button on the login page is displayed incorrectly  #4002

    ### Type of change

    - [x] New Feature (non-breaking change which adds functionality)

commit 0bca46ac3aa22c153c0ffe368cb0da9271f6ab62
Author: Zhichang Yu <yuzhichang@gmail.com>
Date:   Fri Dec 13 13:43:56 2024 +0800

    Migrate infinity at startup (#3858)

    ### What problem does this PR solve?

    Migrate infinity at startup

    #3809
    https://github.com/infiniflow/infinity/issues/2321

    ### Type of change

    - [x] New Feature (non-breaking change which adds functionality)

commit 1ecb687c5192414e2adfe89325447a022717f843
Author: liuhua <10215101452@stu.ecnu.edu.cn>
Date:   Fri Dec 13 10:25:52 2024 +0800

    Fix bugs in agent api and update api document (#3996)

    ### What problem does this PR solve?

    Fix bugs in agent api and update api document

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)
    - [x] New Feature (non-breaking change which adds functionality)

    ---------

    Co-authored-by: liuhua <10215101452@stu.ecun.edu.cn>

commit 68d46b2a1e3ed98ca11c9116b442bbcb11f51e3e
Author: Luo Pan <45253432+unsw-luopan@users.noreply.github.com>
Date:   Fri Dec 13 08:50:58 2024 +0800

    Fix bug in hierarchical_merge function (#4006)

    ### What problem does this PR solve?

    Fix hierarchical_merge function. From idx vs. actual value to actual
    value vs. actual value.
    Related issue #4003

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

    Co-authored-by: luopan <luopan@example.com>

commit 7559bbd46db0bd6814953788200255ca095ee57e
Author: Kevin Hu <kevinhu.sh@gmail.com>
Date:   Fri Dec 13 08:50:32 2024 +0800

    Component debugging funcionality. (#4012)

    ### What problem does this PR solve?

    #3993
    ### Type of change

    - [x] New Feature (non-breaking change which adds functionality)

commit 275b5d14f2e0bc16a51ce993f83b2b2f964c4967
Author: Jin Hai <haijin.chn@gmail.com>
Date:   Thu Dec 12 20:34:46 2024 +0800

    Fix json file parse (#4004)

    ### What problem does this PR solve?

    Fix json file parsing

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

    ---------

    Signed-off-by: jinhai <haijin.chn@gmail.com>

commit 9ae81b42a3cfd4e547ffc0cd04b65016d69f0780
Author: writinwaters <93570324+writinwaters@users.noreply.github.com>
Date:   Thu Dec 12 19:46:53 2024 +0800

    Updated UI (#4011)

    ### What problem does this PR solve?

    ### Type of change

    - [x] Documentation Update

commit d6c74ff131d1c9868884c8ba77e68ffe87ff4558
Author: so95 <is.thaison@gmail.com>
Date:   Thu Dec 12 18:26:44 2024 +0700

    Add mssql support (#3985)

    some thing
    -  execsql  add connection mssql
    - fix bug duckduckgo-search rate limit
    - update typo vi res

    ---------

    Co-authored-by: Kevin Hu <kevinhu.sh@gmail.com>

commit e8d74108a575ac2db53f663789baef3e8663c1a2
Author: Roccat <153699410+lizheng419@users.noreply.github.com>
Date:   Thu Dec 12 19:00:34 2024 +0800

    Fix: Completion AttributeError: 'list' object has no attribute 'get' (#3999)

    ### What problem does this PR solve?

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

    Co-authored-by: lizheng@ssc-hn.com <lizheng@ssc-hn.com>

commit c8b1a564aa0d72ec528c152cdf6b70cf9d14fd80
Author: Zhichang Yu <yuzhichang@gmail.com>
Date:   Thu Dec 12 17:47:39 2024 +0800

    Replaced md5 with xxhash64 for chunk id (#4009)

    ### What problem does this PR solve?

    Replaced md5 with xxhash64 for chunk id

    ### Type of change

    - [x] Refactoring

commit 301f95837c7e72e1929ebb2c7a4c99308371ecad
Author: Zhichang Yu <yuzhichang@gmail.com>
Date:   Thu Dec 12 16:38:03 2024 +0800

    Try to reuse existing chunks (#3983)

    ### What problem does this PR solve?

    Try to reuse existing chunks. Close #3793
    ### Type of change

    - [x] New Feature (non-breaking change which adds functionality)

commit 835fd7abcdcbca3f5f12b5316c4857f0f975c210
Author: writinwaters <93570324+writinwaters@users.noreply.github.com>
Date:   Thu Dec 12 11:45:59 2024 +0800

    Updated RAGFlow edition descriptions (#4001)

    ### What problem does this PR solve?

    ### Type of change

    - [x] Documentation Update

commit bb8f97c9cd770a0fdd879972cfb9492321b668cf
Author: writinwaters <93570324+writinwaters@users.noreply.github.com>
Date:   Thu Dec 12 09:57:52 2024 +0800

    UI updates + RAGFlow image description (#3995)

    ### What problem does this PR solve?

    ### Type of change

    - [x] Documentation Update

commit 6d19294ddc200454f37136635f73c9c803315761
Author: Kevin Hu <kevinhu.sh@gmail.com>
Date:   Wed Dec 11 19:23:59 2024 +0800

    Support debug components. (#3994)

    ### What problem does this PR solve?

    #3993

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

commit f61c276f74cd47d04ef84f3c2b577efd0e7395e7
Author: Jin Hai <haijin.chn@gmail.com>
Date:   Wed Dec 11 18:39:09 2024 +0800

    Update comment (#3981)

    ### What problem does this PR solve?

    _Briefly describe what this PR aims to solve. Include background context
    that will help reviewers understand the purpose of the PR._

    ### Type of change

    - [x] Documentation Update

    ---------

    Signed-off-by: Jin Hai <haijin.chn@gmail.com>
    Co-authored-by: writinwaters <93570324+writinwaters@users.noreply.github.com>

commit 409acf0d9fb4d47fdfb81437f1028ae36ea4c968
Author: balibabu <cike8899@users.noreply.github.com>
Date:   Wed Dec 11 16:29:17 2024 +0800

    Fix:  Fixed the issue where two consecutive indexes were displayed incorrectly #3839 (#3988)

    ### What problem does this PR solve?

    Fix: Fixed the issue where two consecutive indexes were displayed
    incorrectly #3839

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

commit 74c6b21f3b996fd1cb8a3ab14b57770ac6a295cc
Author: liuhua <10215101452@stu.ecnu.edu.cn>
Date:   Wed Dec 11 12:38:57 2024 +0800

    Update api documents (#3979)

    ### What problem does this PR solve?

    Update api documents

    ### Type of change

    - [x] Documentation Update

    Co-authored-by: liuhua <10215101452@stu.ecun.edu.cn>

commit beeacd3e3f48f98aa801bfdf26d9ff2895c81c3a
Author: Kevin Hu <kevinhu.sh@gmail.com>
Date:   Wed Dec 11 11:44:59 2024 +0800

    Fix exec sql exception issue. (#3982)

    ### What problem does this PR solve?
    #3978

    ### Type of change

    - [x] Bug Fix (non-breaking change which fixes an issue)

commit 95259af68f7231c1774735ebdd76862dea61dcb0
Author: so95 <is.thaison@gmail.com>
Date:   Wed Dec 11 10:12:57 2024 +0700

    update typo vietnamese (#3973)

    update typo vietnamese

    ### Type of change
    - [x] Refactoring

    ---------

    Co-authored-by: Yingfeng <yingfeng.zhang@gmail.com>
    Co-authored-by: Jin Hai <haijin.chn@gmail.com>
    Co-authored-by: bill <yibie_jingnian@163.com>

commit 855455006bcbee40353c52360ff251f6f9dc0419
Author: Scott Davidson <49713135+sd109@users.noreply.github.com>
Date:   Wed Dec 11 03:10:33 2024 +0000

    Disable SQL DB binlog in Helm chart (#3976)

    ### What problem does this PR solve?

    The initial Helm chart implementation added in #3815 suffers from an
    issue where the 5GB data volume for the SQL DB is filled up with
    [binlog](https://dev.mysql.com/doc/refman/8.4/en/binary-log.html) files
    after just a few days. Since the app uses a non-replicated SQL DB config
    I think it makes sense to disable the binlog in the SQL DB container.
    This is achieved by simply adding the required argument to the container
    startup command.

    ### Type of change

    - [X] Bug Fix (non-breaking change which fixes an issue)