Fix: Resolve inconsistency in APIToken dialog_id field definition
The `dialog_id` field was inconsistently defined:
- In the `migrate_db()` function, it was set to `null=True`.
- In the model class, it was defined as `null=False`.

This inconsistency caused an issue during the initial deployment where the database table did not allow `dialog_id` to be null. As a result, calling `APITokenService.save(**obj)` in `system_app.py` raised the following error:

```
peewee.IntegrityError: null value in column "dialog_id" violates not-null constraint
```